# Generated by Django 3.2.7 on 2021-11-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transactions_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('S', 'Student Loan'), ('P', 'Personal Loan'), ('M', 'House/Car Loan'), ('B', 'Business Loan'), ('O', 'Others')], max_length=1)),
                ('max_amount', models.IntegerField()),
                ('max_duration', models.DurationField()),
                ('interest_rate', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
