# Generated by Django 3.2.7 on 2021-11-26 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('LID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('P', 'P'), ('U', 'Unpaid'), ('O', 'Overdue'), ('F', 'Flaw')], max_length=1)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.products')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('LID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loan')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
