# Generated by Django 3.2.7 on 2021-11-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_loan_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
