# Generated by Django 3.2.7 on 2021-11-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211126_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_amount',
            field=models.IntegerField(default=0),
        ),
    ]
